#!/bin/bash
#PBS -l walltime=00:05:0
#PBS -l select=1:ncpus=1

# this is a very simple example of a PBS script,
# actually, you would not need to run this using the cluster, or a queuing system, but let's start
# with something very simple

cd $PBS_O_WORKDIR
echo "Hello World!" > log_from_very_simple_job
echo "This job is running on node `hostname -f`" >> log_from_very_simple_job
echo "The working directory of the job is $PBS_O_WORKDIR" >> log_from_very_simple_job
echo "To validate we are at the desired location: `pwd`" >> log_from_very_simple_job
echo "I can see the following files in the working directory: `ls`" >> log_from_very_simple_job
