#!/bin/bash
#PBS -l walltime=00:30:0
#PBS -l select=1:ncpus=1:scratch_local=1gb

echo "$PBS_JOBID is running on node `hostname -f` in a scratch directory $SCRATCHDIR" >> $PBS_O_WORKDIR/jobs_info.txt

# SCRATCHDIR : the absolute path of the scratch directory assigned to the job on the node.
# PBS_O_WORKDIR : the absolute path of the current working directory of the qsub command

# test if scratch directory is set
test -n "$SCRATCHDIR"     || { echo >&2 "Variable SCRATCHDIR is not set!"; exit 2; }
# if your application writes temporary files, it is recommended to set the TMPDIR variable to the scratch directory
export TMPDIR=$SCRATCHDIR || { echo >&2 "Variable SCRATCHDIR is not set!"; exit 2; }

# load required modules, if needed (there will be a separate example on module X singularity X own compiled python, but for now, let's just load a module)
module add python36-modules-gcc || { echo >&2 "Error loading python36-modules-gcc!"; exit 4; }
pip3.6 list                     || { echo >&2 "Error while running pip3.6 list!";    exit 4; }

# copy input files to scratch directory (we assume the files are in the same directory as the script, 
# but you can change it to any other directory by changing the path in the command below)
cp -r $PBS_O_WORKDIR/* $SCRATCHDIR || { echo >&2 "Error while copying input file(s)!"; exit 3; }
# or
# cp -r /storage/praha1/home/<username>/jobs/my_awesome_job_dir $SCRATCHDIR || { echo >&2 "Error while copying input file(s)!"; exit 3; }

# move into scratch directory
cd $SCRATCHDIR

# you can run your application here:
# run your python script, possibly with arguments and data (now at scratch), e.g.:
python3.6 my_awesome_job.py --input profile.csv --output results.csv > log 2>&1 || { echo >&2 "Error while running my_awesome_job.py!"; exit 5; }

mv results.csv     $PBS_O_WORKDIR/  || { echo >&2 "Error while copying results!"; exit 6; }  

# clean the SCRATCH directory!!!
clean_scratch
